### ISSUE TITLE
Restart needed for every restart of backend server

### ISSUE THREAD

**Issue by hmeerlo** [tutumcloud/tutum-docker-clusterproxy#16]
Hi,

currently I have to stop and start the haproxy container whenever I have stopped and started one of my backend containers. This is because haproxy correctly signals it as being down but never sees it coming back up again because the backend container got a new IP address and the LINK environment variables are not updated for that, only the /etc/hosts. So maybe it is a good idea to change the code so that it gets the IP address of the container from /etc/hosts instead of the env vars?

Regards,
Herman

**Comment by hmeerlo** [comment]
I created a pull request, thought I might as well just fix it myself :-)

**Comment by fermayo** [comment]
Hello,

Yes, you are right, we should not rely on environment variables for discovering backend servers. Your PR is a first step towards that - we are working on a DNS-based service discovery system on Tutum that is compatible with Docker links, so I think this is perfect.

@tifayuki can you please review and merge?

Thanks!

**Comment by schmunk42** [comment]
Is this feature implemented? I have a similar problem, because I need to redeploy the haproxy on tutum for every config change.

Is there a way to apply the config and keep the proxy running?

It'd also be nice, if the containers could link the proxy to update the vHost settings.
