### ISSUE TITLE
Multiple domains to one container

### ISSUE THREAD

**Issue by memolipd** [tutumcloud/tutum-docker-clusterproxy#21]
I have an nginx container hosting several static sites, is there a way to point several domains to a single container?

**Comment by fermayo** [comment]
In that case, an external HAProxy cannot do anything. Your nginx server has to be configured with virtual hosts to serve one static site or another based on the `Host` header.

**Comment by memolipd** [comment]
Hi, yep my nginx is setup correctly on the container and serving all the sites correctly, the issue is I want to run other containers on the node at port 80 as well, I know I can point different different domains to different containers, but can I point several domains to one container using HAProxy?

**Comment by tifayuki** [comment]
I think you can try something like this:
```
docker run -d --name webapp tutum/hello-world

docker run -d --link webapp:webapp1 --link webapp:webapp2 -e VIRTUAL_HOST="webapp1=www.webapp1.com, webapp2=www.webapp2.com" -p 80:80 tutum/haproxy
```
This will generate a configuration file shown as bellow:
```
global
  log 127.0.0.1 local0
  log 127.0.0.1 local1 notice
  maxconn 4096
  pidfile /var/run/haproxy.pid
  user haproxy
  group haproxy
  daemon
defaults
  log     global
  mode http
  option redispatch
  option httplog
  option dontlognull
  timeout connect 5000
  timeout client 50000
  timeout server 50000
frontend default_frontend
  bind 0.0.0.0:80
  acl host_WEBAPP2 hdr(host) -i www.webapp2.com
  use_backend WEBAPP2_cluster if host_WEBAPP2
  acl host_WEBAPP1 hdr(host) -i www.webapp1.com
  use_backend WEBAPP1_cluster if host_WEBAPP1
backend WEBAPP2_cluster
  balance roundrobin
  server WEBAPP2 172.17.0.36:80
backend WEBAPP1_cluster
  balance roundrobin
  server WEBAPP1 172.17.0.36:80
```

**Comment by memolipd** [comment]
Yep that should do it, but tutum's site UI does not let you add the same service more than once, guess it'll be a API only feature

**Comment by fermayo** [comment]
We are working to fix that on Tutum :-)

**Comment by ianneub** [comment]
@memolipd This seems to work now, I've been testing this today.

**Comment by develar** [comment]
Workaround doesn't work for me.

Example: 

1) haproxy VIRTUAL_HOST env value:
ROOT=develar.org, RP=routeplanner.develar.org, MTS1=a.tile.develar.org, MTS2=b.tile.develar.org, MTS3=c.tile.develar.org, MTS4=tile.develar.org

2) mapsforge-tile-service added multiple times, ALIAS to serviceNameN (MTS1, MTS2, MTS3, MTS4).

Generated configuration:
[haproxy-1] 2015-03-06T10:12:04.102487086Z frontend default_frontend
[haproxy-1] 2015-03-06T10:12:04.102487086Z   bind 0.0.0.0:80
[haproxy-1] 2015-03-06T10:12:04.102487086Z   acl host_ROUTEPLANNER_DEVELAR_ORG hdr(host) -i routeplanner.develar.org
[haproxy-1] 2015-03-06T10:12:04.102487086Z   use_backend ROUTEPLANNER_DEVELAR_ORG_cluster if host_ROUTEPLANNER_DEVELAR_ORG
[haproxy-1] 2015-03-06T10:12:04.102487086Z   acl host_B_TILE_DEVELAR_ORG hdr(host) -i b.tile.develar.org
[haproxy-1] 2015-03-06T10:12:04.102487086Z   use_backend B_TILE_DEVELAR_ORG_cluster if host_B_TILE_DEVELAR_ORG
[haproxy-1] 2015-03-06T10:12:04.102487086Z   acl host_C_TILE_DEVELAR_ORG hdr(host) -i c.tile.develar.org
[haproxy-1] 2015-03-06T10:12:04.102487086Z   use_backend C_TILE_DEVELAR_ORG_cluster if host_C_TILE_DEVELAR_ORG
[haproxy-1] 2015-03-06T10:12:04.102487086Z   acl host_A_TILE_DEVELAR_ORG hdr(host) -i a.tile.develar.org
[haproxy-1] 2015-03-06T10:12:04.102487086Z   use_backend A_TILE_DEVELAR_ORG_cluster if host_A_TILE_DEVELAR_ORG
[haproxy-1] 2015-03-06T10:12:04.102487086Z   acl host_TILE_DEVELAR_ORG hdr(host) -i tile.develar.org
[haproxy-1] 2015-03-06T10:12:04.102487086Z   use_backend TILE_DEVELAR_ORG_cluster if host_TILE_DEVELAR_ORG
[haproxy-1] 2015-03-06T10:12:04.102487086Z   acl host_DEVELAR_ORG hdr(host) -i develar.org
[haproxy-1] 2015-03-06T10:12:04.102487086Z   use_backend DEVELAR_ORG_cluster if host_DEVELAR_ORG
[haproxy-1] 2015-03-06T10:12:04.102487086Z backend ROUTEPLANNER_DEVELAR_ORG_cluster
[haproxy-1] 2015-03-06T10:12:04.102487086Z   balance roundrobin
[haproxy-1] 2015-03-06T10:12:04.102487086Z   server RP_1 10.7.0.5:80
[haproxy-1] 2015-03-06T10:12:04.102487086Z backend B_TILE_DEVELAR_ORG_cluster
[haproxy-1] 2015-03-06T10:12:04.102487086Z   balance roundrobin
[haproxy-1] 2015-03-06T10:12:04.102487086Z backend C_TILE_DEVELAR_ORG_cluster
[haproxy-1] 2015-03-06T10:12:04.102487086Z   balance roundrobin
[haproxy-1] 2015-03-06T10:12:04.102487086Z backend A_TILE_DEVELAR_ORG_cluster
[haproxy-1] 2015-03-06T10:12:04.102487086Z   balance roundrobin
[haproxy-1] 2015-03-06T10:12:04.102487086Z backend TILE_DEVELAR_ORG_cluster
[haproxy-1] 2015-03-06T10:12:04.102487086Z   balance roundrobin
[haproxy-1] 2015-03-06T10:12:04.102487086Z backend DEVELAR_ORG_cluster
[haproxy-1] 2015-03-06T10:12:04.102487086Z   balance roundrobin
[haproxy-1] 2015-03-06T10:12:04.102487086Z   server ROOT_1 10.7.0.3:80


The problem — I don't see "server" entry for backend *_TILE_DEVELAR_ORG_cluster. Only develar.org and routeplanner.develar.org work. *tile.develar.org return error "No server is available to handle this request."

**Comment by develar** [comment]
Workaround doesn't work due to https://github.com/tutumcloud/tutum-docker-clusterproxy/issues/7 "Do not add duplicate backend routes"

**Comment by memolipd** [comment]
I got round the problem by running the several containers, each one having
the same image and then using haproxy to point each domain to each
container.

Not ideal, but it works.
ᐧ

*Paolo Memoli*
07535020998

100 Shapes
100shapes.com <http://www.100shapes.com/>

Registered No. 07836950
Registered Office: 5 Cape Yard, Wapping, London, E1W 2JU
VAT #: GB136 1292 30

This e-mail and any attachments may contain confidential material for the
sole use of the intended recipient(s). Any review or distribution by others
is strictly prohibited. If you are not the intended recipient, please
contact the sender and delete all copies

**Comment by develar** [comment]
Workaround works fo me. Tutum support  quickly helped me — I have to specify backend port if container exposed port is not equals to 80 (it is unrelated not implemented feature to get correct port automatically).

**Comment by tifayuki** [comment]
I added an environment variable `HDR` and if you set `--env HDR=hdr_end`, virtual host(say, `node.io`) will match domain `*node.io`
