### ISSUE TITLE
ulimit-too-low errors

### ISSUE THREAD

**Issue by dts** [tutumcloud/tutum-docker-clusterproxy#33]
If I allow maxconn to be the default (4096), haproxy complains that ulimit isn't set high enough.  I've googled a fair amount, and there doesn't seem to be a consensus on how to do this for docker systems, and a none of the docker-specific solutions worked on the tutum nodes that I have, because /etc/init/ and /etc/init.d/ had no references to docker, etc.  For now, I have just lowered MAXCONN to a number that doesn't interfere with ulimit, but this won't work long term.

**Comment by fermayo** [comment]
can you try to launch it with `--privileged`? That should allow haproxy to set its own `ulimit`.

**Comment by dts** [comment]
Perfect.  That works.  However, isn't it not the best idea to run outward-facing containers with --privileged, or am I mistaking what "privileged" does exactly?
