### ISSUE TITLE
Error: Name or service not known

### ISSUE THREAD

**Issue by renfredxh** [tutumcloud/tutum-docker-clusterproxy#37]
I'm running this container on Tutum hosted on Digital Ocean. I have the haproxy container sitting in front of an app container. Occasionally while monitoring log entries, an exception pops up from the haproxy container:

```
Traceback (most recent call last): 
  File "/haproxy.py", line 292, in <module> 
     backend_routes = get_backend_routes(os.environ) 
    File "/haproxy.py", line 119, in get_backend_routes 
      add_port['addr'] = socket.gethostbyname(container_name.lower().replace("_", "-")) 
  gaierror: [Errno -2] Name or service not known 
  ERROR:__main__:Error: [Errno -2] Name or service not known
```

When it comes up, usually it's followed by the same exception a few hundred times within a few seconds. It happens a few times every day or so. Any idea what the issue here could be?

**Comment by tifayuki** [comment]
@fermayo Is it has anything to do with the DNS ?

**Comment by fermayo** [comment]
this seems like a temporary issue with our DNS service. However, we do not inject hostnames in environment variables anymore, so you shouldn't see this if you redeploy the service. Also, it seems that you are not giving "API roles" to the service - if you do, it will be able to reconfigure itself automatically.

**Comment by renfredxh** [comment]
I redeployed and gave API roles to the service, and the issue with exceptions showing up in the logs seems to be resolved for now. Thanks for the advice!
