### ISSUE TITLE
Do not require 20-40 seconds downtime to serve newly added services in Tutum

### ISSUE THREAD

**Issue by motin** [tutumcloud/tutum-docker-clusterproxy#38]
Service redeployment equals downtime. Instead of querying tutum api for linked services, another mode could have tutum/haproxy query containers with a specific tag instead. This way, the haproxy can start serving new virtual hosts without downtime.

**Comment by tifayuki** [comment]
Tutum announced stream api using websocket several days ago. I will update this image to use it instead of the polling ASAP. After that, haproxy should be able to update its configuration in "real-time"

**Comment by motin** [comment]
That is great, to skip polling, but it does not take away the need to redeploy the haproxy service when new services need to be proxied. 

Example:
Say two virtual hosts are being served in Tutum:
```
                                                     |---- container 1
                              |----- service 1 ----- |---- container 2
                              |   (virtual host 1)   |---- container 3
internet --- tutum/haproxy--- |
                              |                      |---- container a
                              |----- service 2 ----- |---- container b
                                  (virtual host 2)   |---- container c
```

Then, I want to add a new service:

```
                                                     |---- container 1
                              |----- service 1 ----- |---- container 2
                              |   (virtual host 1)   |---- container 3
internet --- tutum/haproxy--- |
                              |                      |---- container a
                              |----- service 2 ----- |---- container b
                              |   (virtual host 2)   |---- container c
                              |                      |---- container i
                              |----- service 3 ----- |---- container ii
                                  (virtual host 3)   |---- container iii
```

This requires me to link the haproxy service to service 3 and then redeploy the haproxy service, resulting in around 30 seconds of downtime for services 1 and 2, which is undesired. 

If instead, services to be proxied were tagged with for instance "proxy-me" and published internal port 80 on an external dynamic port, then the need for linking would not be necessary (since the ip and port is available via the tutum API), and we could just tag service 3 with "proxy-me" and have the haproxy service start proxying service 3 without any downtime to and other service.

**Comment by fermayo** [comment]
To be honest, updating the service with the new link should be enough for the haproxy to reconfigure itself to send requests to the new backend, without the need to redeploy it. We should support updating links in Tutum without redeploying if the service does not need the environment variables.

**Comment by motin** [comment]
@fermayo That would be the best solution indeed. Keep us posted about when it may be possible to try it out! Thanks :)

**Comment by motin** [comment]
It seems that the latest Tutum updates allows service discovery across stacks without needing links https://support.tutum.co/support/solutions/articles/5000012181-service-discovery-and-links - is this relevant to be leveraged in a solution that does not require service downtime to detect new backends?

**Comment by motin** [comment]
@fermayo Any updates on this?

**Comment by fermayo** [comment]
Still in the backlog, sorry, but will be done in the next few days!

**Comment by tifayuki** [comment]
I have updated haproxy in staging that when using tutum, it reads everything (vhost, links) from tutum API. Now it is pending on the server side.

**Comment by fermayo** [comment]
This is now implemented.

**Comment by motin** [comment]
Great news, thanks! Will try it out soon enough :)
