### ISSUE TITLE
Multiple VIRTUAL_HOSTs for same service

### ISSUE THREAD

**Issue by cvwj** [tutumcloud/tutum-docker-clusterproxy#46]
Currently the haproxy image supports just 1 domain name for a service through the VIRTUAL_HOST variable (set on the linked service).
Would it be possible to support multiple domain names for the same service behind the haproxy? e.g. callings it VIRTUAL_HOSTS=alias1.example.com,alias2.example.com

**Comment by motin** [comment]
+1 I just came here now to file this exact same issue :)

**Comment by KingScooty** [comment]
:+1:

**Comment by tifayuki** [comment]
https://github.com/tutumcloud/tutum-docker-clusterproxy/commit/e1acd0b076e1dbd2930da78760d07b9c194101ab

**Comment by motin** [comment]
Does this work also when running in Tutum?
Should the linked services use VIRTUAL_HOSTS=alias1.example.com,alias2.example.com ?

**Comment by tifayuki** [comment]
Yes, I tested manually on Tutum and it works
