### ISSUE TITLE
Feature request: port mapping

### ISSUE THREAD

**Issue by mwienk** [tutumcloud/tutum-docker-clusterproxy#5]
Hey,

I'm running my web server on port 8080, but I want the load balancer to work on port 80. Currently, this is not supported without editing the Dockerfile. But I think it should be able to optionally specify a BACKEND_PORT in the env settings to support port mappings.

Kind regards

**Comment by memolipd** [comment]
the solution provided doesn't work if you have several containers on several ports, a BACKEND_PORT variable (set on proxied-container's envs) would fix this issue

**Comment by fabfuel** [comment]
I proposed a pull request, which solves this issue
https://github.com/tutumcloud/tutum-docker-clusterproxy/pull/24
Let's see if it gets merged.

In the meantime you can use this container, it's the same as the one from the pull request:
https://registry.hub.docker.com/u/fabfuel/haproxy/

Best
Fabian

**Comment by tifayuki** [comment]
Specifying BACKEND_PORT and FRONTEND_PORT could solve this, now

**Comment by memolipd** [comment]
The current work around does not work for multiple containers with multiple backend ports.

In my case, I have several containers hosting different services (each with a different port) on our office node, and I'd like to use haproxy to point subdomains at the relevant services. Is this possible?

**Comment by tifayuki** [comment]
Maybe you can chain harpoxy container together to do that

**Comment by motin** [comment]
@memolipd https://github.com/tutumcloud/tutum-docker-clusterproxy/pull/35 enables different backend services with different ports when running in Tutum. HAProxy certainly works with this. What is missing is a PR with some python magic that enables haproxy.py to correctly gather the available backend services without knowing of their exposed backend port when not running in Tutum - or make your office node a Tutum Bring-your-own-node :)
