### ISSUE TITLE
haproxy config is not updated when a container is terminated

### ISSUE THREAD

**Issue by ehacke** [tutumcloud/tutum-docker-clusterproxy#53]
The tutum_event_handler() does not trigger run_tutum() when a container is terminated manually.

**Comment by tifayuki** [comment]
It shouldn't. I have test case for terminating a container:
https://github.com/tutumcloud/tutum-docker-clusterproxy/blob/master/Makefile#L168

**Comment by ehacke** [comment]
@tifayuki I see. 

Wouldn't that mean that there would be a server that no longer exists left in the backend definition? And wouldn't that mean that haproxy will then occasionally route traffic to a non-existent server? 

Or does haproxy blacklist a backend server if it does not respond?

**Comment by tifayuki** [comment]
Good point. The terminated route should be removed from the definition and trigger haproxy to reload. I didn't check the definition, my bad.

There is health check in haproxy. When  a backend route is not reachable anymore, haproxy will not pick up that route. I will add the health check settings in the next version.

**Comment by ehacke** [comment]
@tifayuki Ah ok, great. That makes sense.

Another thing, considering that you are monitoring the state of the containers via the API, if the state changes away from "Running", they should immediately be removed from haproxy backend definition until such time as they are "Running" again.

For example, during the time that a container is being redeployed, it's unreachable, and therefore shouldn't be in the round robin rotation.

**Comment by tifayuki** [comment]
Yes, in my code, all the the event states other than "In progress", "Pending", "Terminating", "Starting", "Scaling", "Stopping" and whose parents are linked services will call `run_tutum`. 

So haproxy will always send API query on Running, Stopped, Terminated events. I will check if the definition is updated. In the meanwhile, it also could be the server returns wrong data.

**Comment by fermayo** [comment]
You should use the `linked_to_container` attribute of the container: https://docs.tutum.co/v2/api/?shell#containers

This attribute has the endpoint information for all containers of all linked services that are in states `Running` or `Terminating`. When a service or container is redeployed, the status will change immediately to `Terminating` even though the container is still running. When the container is stopped/terminated, it will be haproxy's health check mechanism the one that will remove it from the list of active backends.

**Comment by bacheson** [comment]
+1 this is not usable in production in it's current state

**Comment by ehacke** [comment]
Thanks!
